HOMEMENU="//*[@id='header']//*[text()='Home']"
HOMESEARCHBOX="//*[@value='Search Products']"
ADDTOCART="//*[@value='Add To Cart']"
GOTOCHECKOUT="//*[@id='fancy_notification_content']//*[@class='go_to_checkout']"
CHECKOUTCARTTABLE="//*[@class='checkout_cart']"
CARTCONTINUEBUTTON="//*[@class='step2']"
FIRSTNAMEFIELD="//*[@title='billingfirstname']"
LASTNAMEFIELD="//*[@title='billinglastname']"
ADDRESSFIELD="//*[@title='billingaddress']"
CITYFIELD="//*[@title='billingcity']"
STATEFIELD="//*[@title='billingstate']"
ZIPFIELD="//*[@title='billingpostcode']"
PHONEFIELD="//*[@title='billingphone']"
SHIPPINGCOUNTRY="//*[@id='current_country']"
SHIPPINGCOUNTRYSELECTION="//*[@id='current_country']//*[text()='USA']"
CHANGECOUNTRY="//*[@id='change_country']"
SHIPPINGCHECKBOX="//*[@id='shippingSameBilling']"
TOTALFIELD="//*[@id='checkout_total']"
PURCHASEBUTTON="//*[@value='Purchase']"
CALCULATEBUTTON="//*[@value='Calculate']"
ACCOUNTUSERNAME="//*[@id='log']"
ACCOUNTPASSWORD="//*[@id='pwd']"
LOGINBUTTON="//*[@id='login']"
YOURDETAILS="//*[@class='user-profile-links']//*[text()='Your Details']"
SAVEPROFILEBUTTON="//*[@value='Save Profile']"
LOGOUTLINK="//*[@id='account_logout']"
REMOVEITEMBUTTON="//*[@value='Remove']"
CHECKOUTBOX="//*[@class='entry-content']"